name: 'Setup deb-s3'
description: 'Setup deb-s3'
inputs:
  install-deb-tools:
    description: 'Install common debian packaging tools'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install deb-s3
      shell: bash
      run: |
        DISTRO_CODENAME=$(lsb_release -cs)
        DISTRO_ID=$(lsb_release -is)
        SUPPORTED_CODENAMES=("bullseye" "jammy" "kinetic")
        SUPPORTED_IDS=("Debian" "Ubuntu")
        
        SUPPORTED="false"
        for SUPPORTED_ID in "${SUPPORTED_IDS[@]}"; do
          if [ "$DISTRO_ID" == "$SUPPORTED_ID" ]; then
            SUPPORTED="true"
          fi
        done
        
        if [ "$SUPPORTED" == "false" ]; then
          echo "Unsupported distro ID: $DISTRO_ID, exiting"
          exit 1
        fi
        
        SUPPORTED="false"
        for SUPPORTED_CODENAME in "${SUPPORTED_CODENAMES[@]}"; do
          if [ "$DISTRO_CODENAME" == "$SUPPORTED_CODENAME" ]; then
            SUPPORTED="true"
          fi
        done
        
        if [ "$SUPPORTED" == "true" ]; then
          echo "Supported distro codename: $DISTRO_CODENAME"
        
          KEY_URL="https://raw.githubusercontent.com/deb-s3/deb-s3/master/deb-s3-archive-keyring.gpg"
          SOURCE="deb http://deb-s3-repo.s3.us-east-2.amazonaws.com/${DISTRO_ID,,}/ $DISTRO_CODENAME main"
        
          if [ "$(id --user)" -eq "0" ]; then
            apt-get update
            apt-get -y install wget
            wget -O /etc/apt/trusted.gpg.d/deb-s3-archive-keyring.gpg "$KEY_URL"
            echo "$SOURCE" | tee -a /etc/apt/sources.list
            apt-get update
            apt-get -y install deb-s3
          else
            sudo apt-get update
            sudo apt-get -y install wget
            sudo wget -O /etc/apt/trusted.gpg.d/deb-s3-archive-keyring.gpg "$KEY_URL"
            echo "$SOURCE" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update
            sudo apt-get -y install deb-s3
          fi
        else
          echo "Unsupported distro codename: $DISTRO_CODENAME, falling back to gem install"
        
          if [ "$(id --user)" -eq "0" ]; then
            apt-get update
            apt-get -y install ruby
            gem install deb-s3
          else
            sudo apt-get update
            sudo apt-get -y install ruby
            sudo gem install deb-s3
          fi
        fi

        if [ "${{ inputs.install-deb-tools }}" == "true" ]; then
          DEPENDENCIES="debhelper devscripts equivs"
          if [ "$(id --user)" -eq "0" ]; then
            apt-get -y install $DEPENDENCIES
          else
            sudo apt-get -y install $DEPENDENCIES
          fi
        fi