name: 'Add STOL apt repository'
description: 'Add STOL apt repository to /etc/apt/sources.list.d'
inputs:
  codename:
    description: 'Codename for sources.list entry'
    required: true
  component:
    description: 'Component for sources.list entry'
    required: false
    default: 'main'
  update:
    description: 'Run apt-get update after adding repository'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Add STOL apt repository
      shell: bash
      run: |
        repo="deb [trusted=yes] https://s3.amazonaws.com/stol-apt-repository ${{ inputs.codename }} ${{ inputs.component }}"
        list="/etc/apt/sources.list.d/stol-apt-repository.list"

        if [ "$(id --user)" -eq "0" ]; then
          echo "$repo" | tee "$list"

          if [ "${{ inputs.update }}" == "true" ]; then
            apt-get update
          fi
        else
          echo "$repo" | sudo tee "$list"

          if [ "${{ inputs.update }}" == "true" ]; then
            sudo apt-get update
          fi
        fi