name: 'Add STOL apt repository'
description: 'Add STOL apt repository to /etc/apt/sources.list.d'
author: 'Leidos'
branding:
  icon: 'archive'  
  color: 'orange'
inputs:
  codename:
    description: 'Codename for sources.list entry'
    required: true
  component:
    description: 'Component for sources.list entry'
    required: false
    default: 'main'
  update:
    description: 'Run apt-get update after adding repository'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Add STOL apt repository
      shell: bash
      run: |
        if [ "$(id --user)" -eq "0" ]; then
          echo "deb [trusted=yes] https://s3.amazonaws.com/stol-apt-repository ${{ inputs.codename }} ${{ inputs.component }}" | tee /etc/apt/sources.list.d/stol-apt-repository.list
        else
          echo "deb [trusted=yes] https://s3.amazonaws.com/stol-apt-repository ${{ inputs.codename }} ${{ inputs.component }}" | sudo tee /etc/apt/sources.list.d/stol-apt-repository.list
        fi

        if [ "${{ inputs.update }}" == "true" ]; then
          if [ "$(id --user)" -eq "0" ]; then
            apt-get update
          else
            sudo apt-get update
          fi
        fi