name: Test custom action

on:
  push:

jobs:
  apt-repo:
    runs-on: ubuntu-latest
    container:
      image: usdotfhwastoldev/carma-base:develop
      options: --user carma
    steps:
      - name: Add STOL apt repository
        uses: codygarver/actions/add-stol-apt-repository@main
        with:
          codename: "develop"
      - name: Install something
        run: |
          if [ "$(id --user)" -eq "0" ]; then
            apt -y install carma-j2735-msgs
          else
            sudo apt -y install carma-j2735-msgs
          fi
      - name: Install deb-s3
        uses: codygarver/actions/setup-deb-s3@main
        with:
          extra-tools: "true"
      - name: Test deb-s3 install
        run: |
          deb-s3 help
